CREATE DATABASE if not EXISTS ucode_web;
USE ucode_web;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    login VARCHAR(30) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL
)

